// // src/AddItemPage.js
// import React, { useState } from "react";
// import { useNavigate } from "react-router-dom";
// import "./AddItemPage.css";

// const AddItemPage = () => {
//   const [newItem, setNewItem] = useState({
//     id: "",
//     image: "",
//     quantity: "",
//     description: "",
//   });
//   const navigate = useNavigate();

//   const handleInputChange = (e) => {
//     const { name, value } = e.target;
//     setNewItem({
//       ...newItem,
//       [name]: value,
//     });
//   };

//   const handleAddItem = () => {
//     if (!newItem.id || !newItem.quantity || !newItem.description) {
//       alert("Please fill out all fields.");
//       return;
//     }

//     const savedData = localStorage.getItem("inventoryData");
//     const inventoryData = savedData ? JSON.parse(savedData) : [];

//     const updatedInventory = [...inventoryData, newItem];
//     localStorage.setItem("inventoryData", JSON.stringify(updatedInventory));

//     setNewItem({ id: "", image: "", quantity: "", description: "" });

//     navigate("/");
//   };

//   return (
//     <div className="add-item-page">
//       <h2>Add New Item</h2>
//       <form
//         onSubmit={(e) => {
//           e.preventDefault();
//           handleAddItem();
//         }}
//       >
//         <label>
//           ID:
//           <input
//             type="text"
//             name="id"
//             value={newItem.id}
//             onChange={handleInputChange}
//           />
//         </label>
//         <label>
//           Image URL:
//           <input
//             type="text"
//             name="image"
//             value={newItem.image}
//             onChange={handleInputChange}
//           />
//         </label>
//         <label>
//           Quantity:
//           <input
//             type="number"
//             name="quantity"
//             value={newItem.quantity}
//             onChange={handleInputChange}
//           />
//         </label>
//         <label>
//           Description:
//           <input
//             type="text"
//             name="description"
//             value={newItem.description}
//             onChange={handleInputChange}
//           />
//         </label>
//         <button type="submit">Add Item</button>
//       </form>
//     </div>
//   );
// };

// export default AddItemPage;

import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { v4 as uuidv4 } from "uuid"; // Import the UUID generator
import "./AddItemPage.css";

// const AddItemPage = ({ setInventoryData, inventoryData }) => {
//   const navigate = useNavigate();
//   const [quantity, setQuantity] = useState(0);
//   const [description, setDescription] = useState("");
//   const [image, setImage] = useState("");

//   const handleAddItem = () => {
//     // Generate a unique ID for the new item
//     const newId = uuidv4();

//     const newItem = {
//       id: newId, // Autogenerated unique ID
//       quantity,
//       description,
//       image,
//     };

//     // Add the new item to the inventory
//     const updatedInventory = [...inventoryData, newItem];

//     // Update the inventory in state and localStorage
//     setInventoryData(updatedInventory);
//     localStorage.setItem("inventoryData", JSON.stringify(updatedInventory));

//     navigate("/");
//   };

//   return (
//     <div className="add-item-page">
//       <h1>Add New Item</h1>
//       <form>
//         <label>
//           Description:
//           <input
//             type="text"
//             value={description}
//             onChange={(e) => setDescription(e.target.value)}
//           />
//         </label>
//         <label>
//           Quantity:
//           <input
//             type="number"
//             value={quantity}
//             onChange={(e) => setQuantity(parseInt(e.target.value))}
//           />
//         </label>
//         <label>
//           Image URL (optional):
//           <input
//             type="text"
//             value={image}
//             onChange={(e) => setImage(e.target.value)}
//           />
//         </label>
//         <button type="button" onClick={handleAddItem}>
//           Add Item
//         </button>
//       </form>
//     </div>
//   );
// };

// export default AddItemPage;


const AddItemPage = ({ inventoryData, setInventoryData }) => {
  const navigate = useNavigate();
  const [quantity, setQuantity] = useState(0);
  const [description, setDescription] = useState("");
  const [image, setImage] = useState("");

  const handleAddItem = () => {
    const newItem = {
      id: uuidv4(),
      quantity,
      description,
      image,
    };

    const updatedInventory = [...inventoryData, newItem];
    setInventoryData(updatedInventory);
    localStorage.setItem("inventoryData", JSON.stringify(updatedInventory));

    setNewItem({ id: "", image: "", quantity: "", description: "" });

    navigate("/home");
  };

  return (
    <div className="add-item-page">
      <h1>Add New Item</h1>
      <form>
        <label>
          Description:
          <input
            type="text"
            value={description}
            onChange={(e) => setDescription(e.target.value)}
          />
        </label>
        <label>
          Quantity:
          <input
            type="number"
            value={quantity}
            onChange={(e) => setQuantity(parseInt(e.target.value))}
          />
        </label>
        <label>
          Image URL (optional):
          <input
            type="text"
            value={image}
            onChange={(e) => setImage(e.target.value)}
          />
        </label>
        <button type="button" onClick={handleAddItem}>
          Add Item
        </button>
      </form>
    </div>
  );
};

export default AddItemPage;
